### PR TITLE
why did you fork??

### PR DESCRIPTION
**Pull request by willcatmeow**

### CODE REVIEW

**Comment by willcatmeow** [comment]
I made this because there's no issues and a had a question.

**Comment by willcatmeow** [comment]
uhhh hello? @Fisch37 ???

**Comment by Fisch37** [comment]
No idea <insert shrug here>

**Comment by willcatmeow** [comment]
so you just decided to?

**Comment by Fisch37** [comment]
I don't even have an idea how forks work tbh

**Comment by Fisch37** [comment]
Yup

**Comment by willcatmeow** [comment]
ok i caan grasp it a little

**Comment by willcatmeow** [comment]
can*

**Pull request closed without merging**
